### ISSUE TITLE
Question about issue_export

### ISSUE THREAD

**Issue by alpesmaritimes34170** [princenyeche/jiraone#121]
Hello,

Comma is used as a CSV delimiter. Is there a way to choose another character as delimiter? I didn't find anything in the documentation.

Thank you.

**Comment by princenyeche** [comment]
Hey @alpesmaritimes34170 

Despite the existence of the delimiter parameter as a keyword argument, it currently isn't utilized in the `issue_export` function. However, I plan to include this feature in the upcoming v0.7.9 release and make it for explicit use. Once implemented, you'll be able to use the `delimiter` parameter when calling the issue_export function, and this parameter will be passed to the `file_writer` and `file_reader` functions. The specified character will then be used as the delimiter for every document created and read

```python
# import statement
issue_export(jql=jql, delimiter=";")
```
In this case, the output of the CSV file will be semi-colon delimited. It's important to note that the delimiter argument only accepts a single character. It's recommended to avoid using characters such as `spaces` or `tabs`, as they might cause conflicts during data extraction. The suggested delimiters to use are either **semi-colon**, **colon**, and **comma** (which is the default).
