### ISSUE TITLE
issue_export stuck

### ISSUE THREAD

**Issue by alpesmaritimes34170** [princenyeche/jiraone#124]
Context : JIRA Datacenter version
jiraone 0.7.9

It seems that there is a regression in issue_export feature. With jiraone 0.7.8, issue_export is running fine with fields option set to []

But with jiraone 0.7.9:

With fields option, set to [], the process is stuck. The export directory is created. Inside it, I can find a temp csv file (temp_file_0.csv) which seems complete. The output is:

Defaulting to comma as CSV separator.
Downloading issue export in CSV format.
<Response [200]>  ::downloading issues at page: 0 of 0

Without fields option, set to [], I get error : 

Traceback (most recent call last):
  File "D:\Tools\Strawberry\scripts\ExportTicketsToCSV2.py", line 25, in <module>
    issue_export(jql=jql_tech_task, folder=Export_Folder,final_file="Defect.csv")
  File "C:\Program Files\Python312\Lib\site-packages\jiraone\reporting.py", line 3296, in export_issues
    field_value_check(_field_names_)  # We'll always check this
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\jiraone\reporting.py", line 3278, in field_value_check
    raise JiraOneErrors(
jiraone.exceptions.JiraOneErrors: <JiraOneError: Unable to find initial field, probably such field "Assignee" doesn't exist for fields argument>

**Comment by princenyeche** [comment]
Hey @alpesmaritimes34170 

Thanks for reporting this issue. Since you're in DC, please let me know if you have this flag (below) turned off for both tests in 0.7.8 and 0.7.9 before running the export.
```python
# previous import statement
LOGIN.api = False

```

**Comment by princenyeche** [comment]
> > Hey @alpesmaritimes34170
> > Thanks for reporting this issue. Since you're in DC, please let me know if you have this flag (below) turned off for both tests in 0.7.8 and 0.7.9 before running the export.
> > ```python
> > # previous import statement
> > LOGIN.api = False
> > ```
> 
> yes it was set like this

Thank you, I'm investigating the problem and will push a new update.

**Comment by princenyeche** [comment]
Hey @alpesmaritimes34170 

Released a new version which should fix this problem on the process being stuck with an empty list. Let me know how it goes for you.

**Comment by alpesmaritimes34170** [comment]
> Hey @alpesmaritimes34170
> 
> Released a new version which should fix this problem on the process being stuck with an empty list. Let me know how it goes for you.

This issue is fixed. Thank you.
