### ISSUE TITLE
Importing Release Versions and Users via CSV in Jira Data Center.

### ISSUE THREAD

**Issue by kalupator** [princenyeche/jiraone#146]
Hello!
1) During import, Release Versions are created with only the version number, but all other columns are empty.
Maybe, Is there a way to import all release versions with all columns?
![image](https://github.com/user-attachments/assets/0ca271c0-dbfe-40d7-8ace-933abf6db147)

2) Is it possible to export via jiraone users with emails and groups via csv?
Now when loading the csv I am asked to specify one domain for email for all users, which is extremely inconvenient.
![Screenshot 2024-12-01 113551](https://github.com/user-attachments/assets/b705db3e-4d41-445f-bdd4-ae36ad6c6a16)

I tried to find the answer in the documentation, but it seems that this functionality is only available for Jira Cloud:
https://jiraone.readthedocs.io/en/latest/apis.html#user
> This class helps to Generate the No of Users on Jira Cloud

I know that there is no such problem with json import, because there you can explicitly specify all users and their groups (I have used this before):
```
    "users": [
        {
            "name": "user.name",
            "groups": [
                "jira-software-users",
                "some-users-group"
            ],
            "fullname": "User Name",
            "email": "user.name@domain.com"
        }
    ]

```
But I can't find such functionality for csv in jiraone.

**Comment by princenyeche** [comment]
@kalupator Yeah, the `User` class is basically for Cloud. It wouldn't be too hard to tweak it for DC or probably subclass it and apply a DC port to achieve what you're looking for. However, if the JSON export does that, a simple way to work around this would be to get the user object from the JSON file and convert it into a CSV file. That would be a much quicker solution to getting that answer.

About the versions, If you're asking about how the import would work, I believe the Jira native importer can import the data as long as it is present. However, I'm not entirely sure I understood the question, please rephrase.

**Comment by kalupator** [comment]
@princenyeche 
Thank you, I wrote a separate script for exporting to json for users.

My question about Fix versions (releases) is that when exporting via jiraone, only the Release version number is exported, but the fields for version (see screenshot) - status, start date, release date, description and etc. are not exported.
After csv import, release versions are created, but the fields status, start date, release date, description are empty - they must be entered manually after import for each release version.
The same behavior is with components. The components themselves are created, but the description, component owner, etc. are not - they must be entered manually after import for each component.

I just wanted to know if jiraone can export this data, I just didn't figure out how?

**Comment by princenyeche** [comment]
@kalupator Thanks for clarifying. It does not have those data, you can only get that from a JSON file. Typically fields such as components, versions and sprints only have their name or number. The other attributes which describes those fields are unfortunately not exported. It is possible to place them in a single column just like the `attachment` fields but then again, the data becomes meaningless when importing to Jira or requires additional modification rather than an easy export/import process.

**Comment by kalupator** [comment]
@princenyeche 
Thank you for the explanation, it's clear.
