### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\x95' in position 1114: character maps to <undefined>

### ISSUE THREAD

**Issue by mvelazquezs** [princenyeche/jiraone#89]
Hi @princenyeche,

I recently reported a bug when downloading incident history via Python on the Atlassian forum.
https://community.atlassian.com/t5/Jira-articles/Extracting-complete-issue-history-via-API/ba-p/1659204

The error is this: **UnicodeEncodeError: 'charmap' codec can't encode character '\x95' in position 1114: character maps to <undefined>**

As you said create a ticket through this way so I ask for your support to be able to resolve it.
Thank you very much

**Comment by princenyeche** [comment]
Hey @mvelazquezs got your request. I'll work on this and push an update asap. Then you can confirm if it then works for you.

**Comment by princenyeche** [comment]
Hey @mvelazquezs I have pushed the update on this issue #89 - Let me know if it fixes the encoding issue for you?
So on windows device it will now explicitly use "utf-8" encoding when writing CSV files. Please update your jiraone library to `v0.6.3` which addresses this issue

**Comment by mvelazquezs** [comment]
Hi @princenyeche ,

Thank you so much, I'll install the latest version, just to confirm, to install this version I have to exceute the command below?

**pip install jiraone==0.6.3** or, How do I have to install the latest version?

Best!

**Comment by princenyeche** [comment]
@mvelazquezs you will need to uninstall the old version and reinstall the new version **v0.6.3**
First do the below
```shell
pip uninstall jiraone
```
Then do
```shell
pip install jiraone==0.6.3
```
or
```shell
pip install jiraone
```
That should install the latest version for you.

**Comment by mvelazquezs** [comment]
Thank you so much @princenyeche
